name: CI/CD helm

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: tolebi1/helm

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: latest

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Helm template (sanity check)
        run: helm template helm ./charts/helmtest

      - name: Helm upgrade/install
        run: |
          helm upgrade --install helm ./charts/helmtest \
            --namespace helm-ns --create-namespace \
            --set image.repository=${{ env.IMAGE_NAME }} \
            --set image.tag=${{ github.sha }}

      - name: Wait for rollout
        run: kubectl -n helm-ns rollout status deploy/helmtest --timeout=180s

      - name: Show services and pods
        run: |
          kubectl -n helm-ns get all